Repository mesonbuild/meson-python, pull requests merged in 2022-09, with the labels that each got.

#133 CI: Run tests against Python from Debian, Fedora, Centos, Gentoo, Archlinux, OpenSUSE, conda-forge
  .github/workflows/ci-sage.yml
Labels: CI

#137 BUG: fix native file override
  mesonpy/__init__.py
Labels: bug

#140 CI: fix triggers for Sage CI jobs
  .github/workflows/ci-sage.yml
Labels: CI

#144 CI: fix PyPy
  .github/workflows/tests.yml
  noxfile.py
Labels: CI

#146 CI: add concurrency control to GitHub Actions workflows
  .github/workflows/checks.yml
  .github/workflows/ci-sage.yml
  .github/workflows/tests-cygwin.yml
  .github/workflows/tests.yml
Labels: CI

#149 TYP: fix a Mypy issue and pin Mypy 0.981
  mesonpy/__init__.py
  noxfile.py
Labels: CI

#143 BUG: fix issues with wheel tags, and add more tests to cover tags
  mesonpy/__init__.py
  tests/packages/executable/example.c
  tests/packages/executable/meson.build
  tests/packages/executable/pyproject.toml
  tests/test_wheel.py
Labels: bug

#147 BUG: Fix meson-python failing on installing install_subdirs
  mesonpy/__init__.py
Labels: bug

#136 DOC: add a simple C extension example
  .gitignore
  docs/examples/spam/meson.build
  docs/examples/spam/pyproject.toml
  docs/examples/spam/src/__init__.py
  docs/examples/spam/src/spammodule.c
  tests/docs/__init__.py
  tests/docs/examples/__init__.py
  tests/docs/examples/conftest.py
  tests/docs/examples/test_spam.py
  tests/test_wheel.py
Labels: documentation

#153 BUG: honor MACOSX_DEPLOYMENT_TARGET
  mesonpy/__init__.py
Labels: bug

#161 BUG: ignore macOS minor version
  mesonpy/__init__.py
  tests/test_wheel.py
Labels: bug
