Repository mesonbuild/meson-python, pull requests merged in 2022-10, with the labels that each got.

#163 BUG: also handle macOS 10.X versions correctly
  mesonpy/__init__.py
  tests/test_wheel.py
Labels: bug

#162 DOC: document how macOS deployment target selection works in more detail
  docs/usage/specific-behaviors.rst
Labels: documentation

#165 TST: update the test for `install_subdir` for fix in meson 0.63.3
  pyproject.toml
  tests/test_wheel.py
Labels: maintenance

#171 Unconditionally require Meson subdir fix
  pyproject.toml
  tests/test_wheel.py
Labels: maintenance

#166 TST: one more fix for the executable bit test
  tests/test_sdist.py
Labels: bug

#176 ENH: use tomllib on Python 3.11+
  mesonpy/__init__.py
  pyproject.toml
Labels: enhancement

#174 CI: set Codecov to "informational" to avoid spurious failures
  codecov.yml
Labels: CI
