Repository mesonbuild/meson-python, pull requests merged in 2022-11, with the labels that each got.

#177 BUG: add generated files to sdist
  mesonpy/__init__.py
  tests/packages/generated-files/example-script.py
  tests/packages/generated-files/example.c
  tests/packages/generated-files/executable_module.py
  tests/packages/generated-files/generate_version.py
  tests/packages/generated-files/meson.build
  tests/packages/generated-files/pyproject.toml
  tests/test_sdist.py
Labels: enhancement

#195 DOC: update copyright statements in LICENSE file
  LICENSE
Labels: documentation

#167 ENH: allow users to pass options directly to Meson
  mesonpy/__init__.py
  mesonpy/_compat.py
  tests/packages/dist-script/meson.build
  tests/packages/dist-script/pyproject.toml
  tests/packages/user-args/meson.build
  tests/packages/user-args/pure.py
  tests/packages/user-args/pyproject.toml
  tests/test_project.py
Labels: enhancement

#209 TST: adding isolated build test
  .github/workflows/ci-sage.yml
  pyproject.toml
  tests/conftest.py
  tests/test_pep518.py
Labels: tests

#210 CI: add pass jobs for both workflows
  .github/workflows/checks.yml
  .github/workflows/ci-sage.yml
  .github/workflows/tests.yml
Labels: CI

#211 MAINT: move config to pyproject.toml
  .flake8
  .github/workflows/tests.yml
  .gitignore
  noxfile.py
  pyproject.toml
  setup.cfg
Labels: maintenance

#213 MAINT: rename the pyproject.toml tool config table to meson-python
  mesonpy/__init__.py
  tests/packages/user-args/pyproject.toml
Labels: maintenance

#194 BUG: Fix breakage when used with Tox
  mesonpy/_util.py
Labels: maintenance

#175 ENH: use system ninja if adequate
  .flake8
  mesonpy/__init__.py
  pyproject.toml
  tests/test_pep517.py
Labels: enhancement

#218 ENH: use dash in config options instead of an underscore
  mesonpy/__init__.py
  tests/test_project.py
Labels: enhancement

#215 ENH: drop dependency on wheel
  meson.build
  mesonpy/__init__.py
  mesonpy/_wheelfile.py
  tests/conftest.py
  tests/test_pep517.py
  tests/test_wheelfile.py
Labels: enhancement

#196 CI: skip tests on documentation changes
  .github/workflows/sage.yml
  .github/workflows/tests.yml
Labels: CI

#227 ENH: include allowed keys in error message
  mesonpy/__init__.py
  tests/test_pep517.py
Labels: enhancement
