Repository mesonbuild/meson-python, pull requests merged in 2023-09, with the labels that each got.

#364 ENH: remove the need for a working directory & other cleanups
  mesonpy/__init__.py
  tests/test_editable.py
  tests/test_options.py
  tests/test_project.py
  tests/test_wheel.py
Labels: maintenance

#471 Sundry cleanups
  mesonpy/__init__.py
Labels: maintenance

#466 DOC: add a howto page on debug builds
  docs/how-to-guides/debug-builds.rst
  docs/index.rst
Labels: documentation

#464 DOC: clean up front page and intro tutorial, state files must be in VCS
  docs/index.rst
  docs/tutorials/introduction.rst
Labels: documentation

#469 ENH: simplify and extend rpath handling
  meson.build
  mesonpy/__init__.py
  mesonpy/_dylib.py
  mesonpy/_elf.py
  mesonpy/_rpath.py
  tests/packages/link-against-local-lib/meson.build
  tests/test_wheel.py
Labels: enhancement

#474 DOC: prepare changelog for 0.14.0 release
  CHANGELOG.rst
Labels: documentation

#470 ENH: add objc and objcpp to the $ARCHFLAGS generated cross file
  mesonpy/__init__.py
Labels: enhancement

#486 ENH: rename the buildir config setting to build-dir
  docs/how-to-guides/build-directory.rst
  docs/how-to-guides/debug-builds.rst
  docs/how-to-guides/editable-installs.rst
  docs/reference/config-settings.rst
  mesonpy/__init__.py
Labels: enhancement

#490 ENH: always require patchelf on Linux
  mesonpy/__init__.py
  tests/test_pep517.py
Labels: enhancement

#493 TST: remove pep518 tests
  tests/conftest.py
  tests/test_pep518.py
Labels: maintenance

#494 BUG: PyPy does not use a special filename suffix for the stable API
  mesonpy/__init__.py
  tests/test_tags.py
  tests/test_wheel.py
Labels: bug

#491 MAINT: simplify logging and use of ANSI color escapes
  mesonpy/__init__.py
  tests/test_output.py
Labels: maintenance
