Repository mesonbuild/meson-python, pull requests merged in 2023-04, with the labels that each got.

#376 BUG: fix reporting of exception messages containing braces
  mesonpy/__init__.py
Labels: release-blocker

#384 ENH: specify meson-python native file as last option to meson setup
  docs/explanations/default-options.rst
  mesonpy/__init__.py
  tests/test_project.py
Labels: maintenance

#390 DOC: update changelog
  CHANGELOG.rst
Labels: documentation

#394 DOC: update readme
  README.md
  README.rst
  pyproject.toml
Labels: documentation

#395 REL: commit for 0.13.0 release, then set version to 0.14.0.dev0
  meson.build
  mesonpy/__init__.py
Labels: maintenance

#396 DOC: add PGP public key for rgommers to security page
  docs/security.rst
Labels: documentation
