Repository mesonbuild/meson-python, pull requests merged in 2024-08, with the labels that each got.

#655 add free threading support to complex.extension
  tests/packages/complex/extension.c
Labels: maintenance

#651 MAINT: pre-commit autoupdate 2024-07-31
  .pre-commit-config.yaml
  pyproject.toml
  tests/test_editable.py
Labels: maintenance

#652 DOC: make the documentation reproducible when rebuilt
  docs/conf.py
Labels: documentation

#656 MAINT: .pre-commit-config.yaml: autoupdate_schedule: quarterly
  .pre-commit-config.yaml
Labels: maintenance

#657 CI: use a token for the Codecov action to upload
  .github/workflows/tests.yml
Labels: CI

#626 Disable abi3 wheel tag for PyPy
  mesonpy/__init__.py
  tests/test_tags.py
  tests/test_wheel.py
Labels: maintenance
