Repository mesonbuild/meson-python, pull requests merged in 2024-10, with the labels that each got.

#682 ci: Update Python versions
  .github/workflows/tests.yml
Labels: CI

#634 DOC: add a brief explanation of build isolation to the tutorial
  docs/tutorials/introduction.rst
Labels: documentation

#690 MAINT: set version to 0.18.0.dev0
  meson.build
  mesonpy/__init__.py
Labels: maintenance

#692 CI: version updates
  .github/workflows/tests.yml
Labels: CI

#699 DOC: update changelog for 0.17.1
  CHANGELOG.rst
Labels: documentation
