Repository mesonbuild/meson-python, pull requests merged in 2025-05, with the labels that each got.

#737 MAINT: switch to PEP639 license declaration for meson-python itself
  pyproject.toml
Labels: maintenance

#745 BUG: fix a problem with symlink support
  mesonpy/__init__.py
  tests/packages/symlinks/meson.build
  tests/packages/symlinks/pyproject.toml
Labels: bug

#746 MAINT: set version to 0.19.0.dev0
  mesonpy/__init__.py
  pyproject.toml
Labels: maintenance

#740 Extend CI
  .github/workflows/tests.yml
Labels: CI

#731 Add support for targeting iOS.
  docs/reference/environment-variables.rst
  docs/reference/meson-compatibility.rst
  mesonpy/__init__.py
  mesonpy/_tags.py
  pyproject.toml
  tests/test_project.py
  tests/test_tags.py
Labels: enhancement

#757 MAINT: enforce string quoting style with ruff
  .pre-commit-config.yaml
  mesonpy/_tags.py
  pyproject.toml
  tests/test_project.py
Labels: maintenance

#758 MAINT: fix ruff configuration in pyproject.toml
  pyproject.toml
Labels: maintenance
